[build]
publish = "dist"
command = "npm run build"

[dev]
publish = "dist"
command = "npm run dev"

[[redirects]]
from = "https://oss-valentine.netlify.app"
to = "https://oss.cards"
status = 301
force = true

[[redirects]]
from = "/create"
to = "/.netlify/functions/save-card"
status = 200

[[redirects]]
from = "/card/*"
to = "/.netlify/builders/view-card"
status = 200

[[redirects]]
from = "/auth/*"
to = "/.netlify/functions/auth-:splat"
status = 200

[[redirects]]
from = "/api/user/:username"
to = "/.netlify/functions/user"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/og/*"
to = "/.netlify/functions/view-og"
status = 200
